# Site
repository: MerlijnQ/modern-resume-theme

# Content configuration version
version: 2

# Personal info
name: Merlijn Mulder
title: Graduate AI student @ RUG
email: m.q.mulder@student.rug.nl

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: MerlijnQ
linkedin_username: merlijn-mulder-a275b5236

# About Section
about_profile_image: /images/profile.jpeg
about_content: |
  Hey there, welcome to my website! The place where you can find out about projects I have worked on. However, let me first introduce myself:
  
  A persistent, enthusiastic, and ambitious student interested in technology and innovation who enjoys working on beta-related group projects. 
  I have a good communicative and results-oriented view, which I have used in multi-cultural environments. I not only demonstrated this at the University of Groningen (RUG)
  but also during an [exchange semester](https://www.linkedin.com/posts/merlijn-mulder-a275b5236_exchange-haskell-wireframes-activity-7288237000871047169-mtWi?utm_source=share&utm_medium=member_desktop&rcm=ACoAADrSPn8BOEDwMcp8qt4GjyhoB4g4mta1q6A) at the Singapore University of Technology and Design!

  Currently, I'm pursuing a master's in AI, specialised in AI engineering, Machine Learning and hybrid intelligence.
  My background includes both academic and industry experience across education, sales, and fundraising whilst thriving in team-oriented environments.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: OOD in BCI
        sub_title: Bachelor thesis project
        caption: 2025
        link_text: Article
        link: https://fse.studenttheses.ub.rug.nl/35683/1/bAI2025MulderMQ.pdf
        description: |
          Together with my supervisor Ivo de Jong, MSc, I am researching out-of-distribution (OOD) Detection within the motor-imagery brain-computer interface Paradigm.
          An image classifier can distinguish a cat from a dog and can also distinguish, using uncertainty techniques that it is presented with an image of a chicken
          on which it wasn't trained; this proves to be a bit more complicated from brain signals. Can we distinguish someone wiggling their feet from raising their arm when
          our deep learning model has not encountered a brain signal portraying raising the arm before?

      - layout: left
        title: Mind Wandering and Auditory Stimuli
        caption: 2025
        link_text: View Paper
        link: https://github.com/MerlijnQ/MerlijnQ.github.io/blob/master/assets/MW_Auditory_stimuly.pdf
        description: |
          Mind wandering (MW) decreases performance in various attention tasks. We investigate how a task-relevant (cue) and a task-irrelevant (distraction) auditory stimulus affect MW in a
          sustained attention response task (SART). Using the ACT-R architecture, we build a simple MW model in which we simulate three conditions, consisting of a condition without an auditory
          stimulus and the different stimuli previously stated. Although MW remained near 50% across conditions, our results reveal that the auditory stimuli affect the timing of MW. Cues 
          significantly reduced MW at moments when a button press was required in response to a visual stimulus. The task-irrelevant condition displayed a similar but less pronounced effect.
          Whilst the paper linked is written by me, this was a group project together with Alexander Müller, Felix Michalak and Nienke Posthumus.

      - layout: left
        title: Blockchain in certificate systems
        caption: 2024
        link_text: View Review
        link: https://github.com/MerlijnQ/MerlijnQ.github.io/blob/master/assets/Blockchain_paper_review.pdf
        description: |
          During my time at SUTD, I wrote a review on the paper Ethereum-Blockchain-Based Technology of Decentralized Smart Contract Certificate System (Xie et al. 2020).
          Digital certificates are vulnerable to tampering, cyberattacks, and voiding. Blockchain and smart contracts offer a transparent, immutable solution. 
          This paper reviews Open Certificates, a proposal using smart contracts in a 3-layer authority system to manage certificate roles.
          While effective in addressing these issues and enabling validation,
          the system has vulnerabilities, such as the election of system managers and the lack of downloadable PDFs for use with less modern institutions. 
          In this review, I propose integrating two other systems to overcome these limitations.

      - layout: left
        title: OOP-style ML DataLoader
        caption: 2024
        link_text: View Description
        link: https://github.com/MerlijnQ/MerlijnQ.github.io/blob/master/assets/OOP_dataLoader.pdf
        description: |
          Together with Jerno Beuker, I developed a Data Loader in Python for machine learning applications following the OOP guidelines. This consisted of a data manager,
          eager loading system, lazy loading system, batch loader and data preprocessing techniques. Whilst the project is not made publicly available at the moment,
          an overview is attached.

      - layout: left
        title: BurgerMeister
        sub_title: App development in Dart & Flutter
        caption: 2022
        description: |
          BurgerMeister is where my journey with big coding-related projects really took off. Based on the app "Untappd", I developed a Flutter and Dart-based application for a client
          desiring such a system for recording where he found the best burgers as part of my final computing science high school project. This was later awarded a 10. Whereas I was responsible for the coding,
          two team members supported me for visuals, documentation and research. Within the final product, the client could record their burger activities, including categories, ratings,
          location, etc. This was filtered and stored in a Firebase database system. Furthermore, the product supported communication between users and allowed them to receive badges when a landmark was reached.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Rijksuniversiteit Groningen
        sub_title: Head Teaching Assitant, Teaching Assistant & Mentor
        caption: September 2023 – now
        quote: 
          Assisting students academically and socially within the AI program.
        description: |
          As a mentor, I help first-year students transfer from high school to university. 
          This includes group and individual sessions one semester long. 
          Currently I am active as Head TA for the courses Introduction to Artificial Intelligence and Autonomous systems. Apart from facilitating tutorials I support the professors in the development of the courses.
          Furthermore, I have been active as a teaching assistant for the courses Basic Scientific Skills, Cognitive Psychology, and Introduction to the Brain.

      - layout: left
        title: MediaMarkt Sontplein
        sub_title: Sales & Solutions Employee
        caption: September 2022 – July 2024
        description: |
          As a part-time sales and solutions employee, I advise customers on the tech products and services offered within the store's computer department
          and help them find the best-fitting solution for their problems. 

      - layout: left
        title: SV Cover (AI Study Association)
        sub_title: Advisory Member
        caption: May 2023 – present
        description: |
          Currently, I am an [advisory member](https://www.linkedin.com/posts/merlijn-mulder-a275b5236_and-that-is-a-wrap-with-this-years-symposium-activity-7300245232678293504-Ckpl?utm_source=share&utm_medium=member_desktop&rcm=ACoAADrSPn8BOEDwMcp8qt4GjyhoB4g4mta1q6A) for the sports committee and the symposium committee within the study association. 
          Previously, as an active member of the study association, I have contributed to organizing the [2024 symposium](https://www.linkedin.com/posts/merlijn-mulder-a275b5236_1-month-ago-on-the-24th-of-april-2024-study-activity-7200062947245649920-6XGi?utm_source=share&utm_medium=member_desktop&rcm=ACoAADrSPn8BOEDwMcp8qt4GjyhoB4g4mta1q6A)  as chairman of the symposium committee, 
          Organizing sports activities as the chairman of the [sports committee](https://www.linkedin.com/posts/merlijn-mulder-a275b5236_sports-keeping-the-body-moving-and-the-blood-activity-7213201569733902336-EGzH?utm_source=share&utm_medium=member_desktop&rcm=ACoAADrSPn8BOEDwMcp8qt4GjyhoB4g4mta1q6A) and organizing the introduction activities 2023
          as a general member of the introduction committee.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Rijksuniversiteit Groningen
        sub_title: MSc Artificial Intelligence
        caption: 2025 – now
        description: |
          I am currently pursuing a master's degree in AI, specializing in Machine Learning and AI Engineering.
            
      - layout: left
        title: Singapore University of Technology and Design
        sub_title: Minor
        caption: 2024
        description: |
          I spent a semester abroad at the Singapore University of Technology and Design. Apart from the cultural experience,
          I learned a lot about implementing compilers using a functional programming language like Haskell, Blockchain development,
          User interface design and Extended Reality technologies and development.

      - layout: left
        title: Rijksuniversiteit Groningen
        sub_title: BSc Artificial Intelligence
        caption: 2022 – 2025
        description: |
          I successfully completed a Bachelor's degree in Artificial Intelligence.

      - layout: left
        title: Rijksuniversiteit Groningen
        sub_title: Teaching Assistant Training
        caption: September 2023
        description: |
          I have successfully completed 20 hours of teaching assistant training with the faculty’s professional development and innovation in education (PIE) and Diversity, Equity, and Inclusion (DEI) teams.  
          Covering 14 hours of didactics and 6 hours of intercultural competencies

  - title: Skills
    layout: text
    content: |
      - Presenting & Public Speaking  
      - Active Listening  
      - Teamwork  
      - Office 365 & LaTeX  
      - Python, Haskell & Dart

  - title: Languages
    layout: text
    content: |
      - **Dutch**: Native speaker  
      - **English**: C1 level  
      - **German**: B2 level

# Footer
footer_show_references: true

# Build settings
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
